### ISSUE TITLE
Does not work on Docker

### ISSUE THREAD

**Issue by nmjmdr** [docusign/docusign-node-client#119]
The latest version Docusign node client does not work on docker.
This is because the file `docusign-esign/src/ApiClient.js` uses require Oauth.js where as the file is OAuth.js (notice the case)

This works ok on windows or mac but does not on linux (and Docker)

We had to use 4.1.0 version of docusign to make it work.

```
Cannot find module './Oauth'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at new exports (/usr/local/checkbox-validator-dev/node_modules/docusign-esign/src/ApiClient.js:119:22)
    at /usr/local/checkbox-validator-dev/node_modules/docusign-esign/src/ApiClient.js:899:22
    at isArray (/usr/local/checkbox-validator-dev/node_modules/docusign-esign/src/ApiClient.js:18:22)
    at Object.<anonymous> (/usr/local/checkbox-validator-dev/node_modules/docusign-esign/src/ApiClient.js:26:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```

**Comment by acooper4960** [comment]
@nmjmdr A fix has been added to the existing RC. Please run npm install docusign-esign@next to receive this fix
