### ISSUE TITLE
TypeError: boolean is not a function in envelopes.js

### ISSUE THREAD

**Issue by nrnaveen** [docusign/DocuSign-Node-Client#26]
TypeError: boolean is not a function

at Request._callback (/node_modules/docusign-node/dsUtils.js:142:7)
    at Request.self.callback (/node_modules/docusign-node/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/node_modules/docusign-node/node_modules/request/index.js:886:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/node_modules/docusign-node/node_modules/request/index.js:837:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

change envelopes.js line 812
dsUtils.makeRequest('Get List of Recipients', options, false, callback); => dsUtils.makeRequest('Get List of Recipients', options, callback);

**Comment by Whoaa512** [comment]
Thanks!
