### ISSUE TITLE
Constructor error

### ISSUE THREAD

**Issue by srajkumar1986** [docusign/docusign-node-client#73]
Hello,
I am receiving the below error on **CoreRecipes.js**. Can anyone please correct what is wrong on this. 

 var loginOps = new authApi.LoginOptions();
                 ^
TypeError: authApi.LoginOptions is not a constructor
at RequestSignatureOnDocument (/root/IdeaProjects/docusignapp/test/Recipes/CoreRecipes.js:51:18)
    at Object.<anonymous> (/root/IdeaProjects/docusignapp/test/Recipes/CoreRecipes.js:959:1)
    at Module._compile (module.js:570:14)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by mmallis87** [comment]
@srajkumar1986 unfortunately the core recipes uses version 2.x of this package. If you want examples that work with the current version (3.x) please see: https://github.com/docusign/docusign-node-client/blob/master/test/SdkUnitTests.js

**Comment by LarryKlugerDS** [comment]
I'm sorry for the problem. I have removed the old Core Recipes repo.

Please try to the current code examples:

Recommended: [Authorization Code Grant example launcher and scenarios](https://github.com/docusign/eg-03-node-auth-code-grant)

[JWT Grant authentication example](https://github.com/docusign/eg-01-node-jwt)
