### ISSUE TITLE
tabs.constructFromObject is not a function

### ISSUE THREAD

**Issue by nolafs** [docusign/docusign-node-client#74]
Hi 

Having issues with node sdk. The models dont seems to export the .constructFromObject method. 

const docusign = require('docusign-esign');
var tab = new docusign.Text();
tab.constructFromObject(data);

This is throwing an error. tab.constructFromObject is not a function. I have checked the source and it is there.

Cheers
Olaf

**Comment by mikeRead** [comment]
Just got this too!
It seems like it throws this error when the template as a drop down in it 
I can reproduct when I
Create a new template
drag a dorpdown
save
run 
```template.listTemplates(accountId, opts, callback)```

STACK:
`{
    "message": "type.constructFromObject is not a function",
    "stack": "TypeError: type.constructFromObject is not a function\n    at Function.exports.convertToType (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:507:23)\n    at S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:512:28\n    at Array.map (native)\n    at Function.exports.convertToType (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:511:23)\n    at Function.exports.constructFromObject (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\model\\Tabs.js:101:37)\n    at Function.exports.constructFromObject (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\model\\Signer.js:212:28)\n    at Function.exports.convertToType (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:507:23)\n    at S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:512:28\n    at Array.map (native)\n    at Function.exports.convertToType (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:511:23)\n    at Function.exports.constructFromObject (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\model\\Recipients.js:87:36)\n    at Function.exports.constructFromObject (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\model\\EnvelopeTemplate.js:170:40)\n    at Function.exports.convertToType (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:507:23)\n    at exports.deserialize (S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:346:20)\n    at S:\\repos\\approach-api-v2\\crm\\node_modules\\docusign-esign\\src\\ApiClient.js:459:26\n    at Request.callback (S:\\repos\\approach-api-v2\\crm\\node_modules\\superagent\\lib\\node\\index.js:816:12)\n    at IncomingMessage.<anonymous> (S:\\repos\\approach-api-v2\\crm\\node_modules\\superagent\\lib\\node\\index.js:1046:12)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"
}`

**Comment by mikeRead** [comment]
also here is the rest api version of the template


```json
{
    "envelopeTemplateDefinition": {
        "templateId": "2ec2f9b0-3b6b-4923-937f-8adc882c133c",
        "name": "Please DocuSign: pdf-sample.pdf",
        "shared": "true",
        "password": "",
        "description": "",
        "lastModified": "2017-12-07T18:06:54.2800000Z",
        "lastModifiedBy": {
            "userName": "mike read",
            "userId": "6784a522-7c74-4d0f-aad0-692d19adffb8",
            "email": "mike@tilefive.com",
            "uri": "/users/6784a522-7c74-4d0f-aad0-692d19adffb8"
        },
        "pageCount": 1,
        "uri": "/templates/2ec2f9b0-3b6b-4923-937f-8adc882c133c",
        "folderName": "Templates",
        "folderId": "8d16ea43-78b2-431b-a915-8d760006bff8",
        "folderUri": "/folders/8d16ea43-78b2-431b-a915-8d760006bff8",
        "owner": {
            "userName": "mike read",
            "userId": "6784a522-7c74-4d0f-aad0-692d19adffb8",
            "email": "mike@tilefive.com"
        }
    },
    "documents": [
        {
            "documentId": "1",
            "uri": "/envelopes/2ec2f9b0-3b6b-4923-937f-8adc882c133c/documents/1",
            "name": "pdf-sample.pdf",
            "order": "1",
            "pages": "1",
            "display": "inline",
            "includeInDownload": "true",
            "signerMustAcknowledge": "no_interaction",
            "templateLocked": "false",
            "templateRequired": "false",
            "documentGroup": "content"
        }
    ],
    "emailSubject": "Please DocuSign: pdf-sample.pdf",
    "emailBlurb": "now",
    "signingLocation": "online",
    "autoNavigation": "true",
    "envelopeIdStamping": "true",
    "authoritativeCopy": "false",
    "notification": {
        "reminders": {
            "reminderEnabled": "false",
            "reminderDelay": "0",
            "reminderFrequency": "0"
        },
        "expirations": {
            "expireEnabled": "true",
            "expireAfter": "120",
            "expireWarn": "0"
        }
    },
    "enforceSignerVisibility": "false",
    "enableWetSign": "true",
    "allowMarkup": "false",
    "allowReassign": "true",
    "recipients": {
        "signers": [
            {
                "defaultRecipient": "false",
                "tabs": {
                    "signHereTabs": [
                        {
                            "stampType": "signature",
                            "name": "SignHere",
                            "tabLabel": "Signature 768423a0-d994-441b-94e8-41e6369a8b20",
                            "scaleValue": 1,
                            "optional": "false",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "118",
                            "yPosition": "435",
                            "tabId": "c1b70619-5e07-4cf7-93d9-75e1bb38c58d",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "fullNameTabs": [
                        {
                            "name": "Full Name",
                            "value": "",
                            "tabLabel": "Name 78d5961c-481f-41ab-888e-69ff3b4b28e0",
                            "font": "lucidaconsole",
                            "bold": "false",
                            "italic": "false",
                            "underline": "false",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "526",
                            "yPosition": "652",
                            "tabId": "026fe17b-05b0-4600-9332-7e96829a0bc9",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "dateSignedTabs": [
                        {
                            "name": "DateSigned",
                            "value": "",
                            "tabLabel": "Date Signed 916400d1-3049-4b60-8371-eabb20fbce2b",
                            "font": "lucidaconsole",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "115",
                            "yPosition": "429",
                            "tabId": "ca90c6b2-baa3-466b-baa8-2e78cdc81def",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "companyTabs": [
                        {
                            "value": "",
                            "required": "true",
                            "locked": "false",
                            "concealValueOnDocument": "false",
                            "disableAutoSize": "false",
                            "tabLabel": "Company 18c2e9c4-5681-4174-92c1-6a79586ff31b",
                            "font": "lucidaconsole",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "115",
                            "yPosition": "586",
                            "tabId": "ad6633c3-b6a9-44c5-b741-043d32652100",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "titleTabs": [
                        {
                            "value": "",
                            "required": "true",
                            "locked": "false",
                            "concealValueOnDocument": "false",
                            "disableAutoSize": "false",
                            "tabLabel": "Title 391d23d0-076c-4767-9fdd-090b95bee4a1",
                            "font": "lucidaconsole",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "190",
                            "yPosition": "520",
                            "tabId": "1422a202-1e73-46a0-a4f9-e64a6481416f",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "textTabs": [
                        {
                            "height": 11,
                            "isPaymentAmount": "false",
                            "validationPattern": "",
                            "validationMessage": "",
                            "shared": "false",
                            "requireInitialOnSharedChange": "false",
                            "requireAll": "false",
                            "name": "ToolTip",
                            "value": "tesetsdasdf",
                            "originalValue": "tesetsdasdf",
                            "width": 78,
                            "required": "true",
                            "locked": "false",
                            "concealValueOnDocument": "false",
                            "disableAutoSize": "false",
                            "maxLength": 4000,
                            "tabLabel": "FrstName",
                            "font": "lucidaconsole",
                            "bold": "false",
                            "italic": "false",
                            "underline": "false",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "391",
                            "yPosition": "69",
                            "tabId": "eedd35ce-13a8-445a-9bf5-ef85e4935685",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "noteTabs": [
                        {
                            "width": 72,
                            "height": 33,
                            "shared": "false",
                            "value": "",
                            "name": "",
                            "tabLabel": "Note 82f8b820-9f6e-4079-9b9c-fa70e796d23d",
                            "font": "lucidaconsole",
                            "bold": "false",
                            "italic": "false",
                            "underline": "false",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "121",
                            "yPosition": "674",
                            "tabId": "90fa003d-a35f-4ad2-8f00-3925598ba9c6",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "checkboxTabs": [
                        {
                            "name": "",
                            "tabLabel": "Checkbox 1",
                            "selected": "false",
                            "shared": "false",
                            "requireInitialOnSharedChange": "false",
                            "required": "false",
                            "locked": "false",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "292",
                            "yPosition": "528",
                            "tabId": "c11e8da3-37ec-49e3-a49c-af4c955f76e6",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        },
                        {
                            "name": "",
                            "tabLabel": "checkbox 2",
                            "selected": "false",
                            "shared": "false",
                            "requireInitialOnSharedChange": "false",
                            "required": "false",
                            "locked": "false",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "292",
                            "yPosition": "551",
                            "tabId": "a06d2c2a-0a05-4f07-ad27-3557f459b24d",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "radioGroupTabs": [
                        {
                            "documentId": "1",
                            "recipientId": "97639843",
                            "groupName": "Radio Group a8254bec-8317-42ee-86c9-1bd84e5660dd",
                            "radios": [
                                {
                                    "pageNumber": "1",
                                    "xPosition": "443",
                                    "yPosition": "613",
                                    "value": "Radio 4",
                                    "selected": "false",
                                    "required": "True",
                                    "locked": "False"
                                },
                                {
                                    "pageNumber": "1",
                                    "xPosition": "442",
                                    "yPosition": "643",
                                    "value": "Radio 5",
                                    "selected": "false",
                                    "required": "True",
                                    "locked": "False"
                                },
                                {
                                    "pageNumber": "1",
                                    "xPosition": "449",
                                    "yPosition": "517",
                                    "value": "Radio 1",
                                    "selected": "false",
                                    "required": "True",
                                    "locked": "False"
                                },
                                {
                                    "pageNumber": "1",
                                    "xPosition": "444",
                                    "yPosition": "551",
                                    "value": "Radio 2",
                                    "selected": "false",
                                    "required": "True",
                                    "locked": "False"
                                },
                                {
                                    "pageNumber": "1",
                                    "xPosition": "448",
                                    "yPosition": "585",
                                    "value": "Radio 3 (default)",
                                    "selected": "true",
                                    "required": "True",
                                    "locked": "False"
                                }
                            ],
                            "shared": "False",
                            "requireInitialOnSharedChange": "false",
                            "requireAll": "false"
                        }
                    ],
                    "listTabs": [
                        {
                            "listItems": [
                                {
                                    "text": "1opt",
                                    "value": "1val",
                                    "selected": "false"
                                },
                                {
                                    "text": "2",
                                    "value": "2val",
                                    "selected": "false"
                                },
                                {
                                    "text": "3",
                                    "value": "3val",
                                    "selected": "false"
                                },
                                {
                                    "text": "4",
                                    "value": "4val",
                                    "selected": "false"
                                },
                                {
                                    "text": "5",
                                    "value": "5val",
                                    "selected": "false"
                                }
                            ],
                            "value": "",
                            "width": 78,
                            "shared": "false",
                            "required": "true",
                            "locked": "false",
                            "requireAll": "false",
                            "tabLabel": "Dropdown a59c81a3-1b59-4606-ad7a-d83b1e8f662a",
                            "font": "lucidaconsole",
                            "bold": "false",
                            "italic": "false",
                            "underline": "false",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "386",
                            "yPosition": "256",
                            "tabId": "8d8b5049-250f-42c2-909d-9cc8184daee2",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ],
                    "emailAddressTabs": [
                        {
                            "name": "EmailAddress",
                            "value": "",
                            "tabLabel": "Email b942de1c-a3ae-4f7a-8ba8-2f4d5f96d22b",
                            "font": "lucidaconsole",
                            "fontColor": "black",
                            "fontSize": "size9",
                            "documentId": "1",
                            "recipientId": "97639843",
                            "pageNumber": "1",
                            "xPosition": "112",
                            "yPosition": "552",
                            "tabId": "442335c5-5b99-45b3-a084-51c85aecba1a",
                            "templateLocked": "false",
                            "templateRequired": "false"
                        }
                    ]
                },
                "signInEachLocation": "false",
                "name": "",
                "email": "",
                "recipientId": "97639843",
                "accessCode": "",
                "requireIdLookup": "false",
                "routingOrder": "1",
                "note": "",
                "roleName": "Signer 1",
                "deliveryMethod": "email",
                "templateLocked": "false",
                "templateRequired": "false",
                "inheritEmailNotificationConfiguration": "false"
            }
        ],
        "agents": [],
        "editors": [],
        "intermediaries": [],
        "carbonCopies": [],
        "certifiedDeliveries": [],
        "inPersonSigners": [],
        "seals": [],
        "recipientCount": "1"
    }
}
```

**Comment by ppurwanto** [comment]
@nolafs That's because `constructFromObject` is _always_ defined as a **static** method for _all_ of the DocuSign objects (e.g., models) that do define it in this library.

I found out about that after I just dug through the codebase and my findings are confirmed by the [official documentation's "(static)" labeling](https://docusign.github.io/docusign-node-client/module-model_Text.html#.constructFromObject):
They're not declared via the **`prototype`** chain (as in `exports.prototype.constructFromObject`); hence, they cannot be used as instance methods (with **`new`** keyword) and must instead be used as static methods directly, such as `docusign.Text.constructFromObject(data)`.

Best,
Peter Purwanto.
